model_list:
  - model_name: deepseek-v4-flash
    litellm_params:
      model: deepseek/deepseek-v4-flash
      api_key: os.environ/DEEPSEEK_API_KEY
  - model_name: deepseek-v4-pro
    litellm_params:
      model: deepseek/deepseek-v4-pro
      api_key: os.environ/DEEPSEEK_API_KEY
  - model_name: bedi/glm-4.7
    litellm_params:
      model: bedi/glm-4.7
      api_key: sk-NEjTXSJQGiGDDZL6F713D67dA7D14972B0407b90C2B137B9
      api_base: https://baotaai.bedicloud.net/v1
      custom_llm_provider: openai
      input_cost_per_token: 6.0e-7
      output_cost_per_token: 2.2e-6
      cache_read_input_token_cost: 1.1e-7

litellm_settings:
  drop_params: true
  num_retries: 3
  request_timeout: 600
  telemetry: false
  success_callback: ["langfuse"]
  callbacks:
    - custom_auth.validator
    - custom_auth.tracker

general_settings:
  master_key: sk-litellm-master-key-1234
